### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Kabeuchi** [Kabeuchi/protospace-34466#1]
https://protospace-34466.herokuapp.com/

**Comment by checker-ms** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が引き続き見受けられましたので修正をお願いします！

[現状]
①投稿に必要な情報が入力されていない場合は、投稿できずにそのページに留まらず、エラーメッセージが表示されてしまう
②新規登録済みのユーザーが、一度ログアウト状態にし、その後必要な情報を入力しても、ログインができない

[修正箇所]
①投稿に必要な情報が入力されていない場合は、投稿できずにそのページに留まること
②必要な情報を入力すると、ログインができること

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません

https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by checker-ms** [comment]
ご提出ありがとうございます！
修正箇所が反映されていないように思います。

コードを修正して、GitHubのリモートリポジトリとHerokuにプッシュはお済みでしょうか？
お手数ですが、本番環境にて、修正内容が反映されていることを確認したのち、再度確認依頼を提出お願いします
